[[contributors]]
name = "doppioslash"
about = "Graphics Programmer"
description = "Writes on <a href=\"//www.shadercat.com\">shadercat.com</a> about Physically Based Shading and Rendering with Rust and Unity."

[contributors.links]
twitter = "doppioslash"
github = "doppioslash"
home = "http://doppioslash.com"

[[contributors]]
name = "nxnfufunezn"
about = "Backend developer and FP enthusiast"

[contributors.links]
twitter = "nxnfufunezn"
github = "nxnfufunezn"

[[contributors]]
name = "bwasty"
about = "Software Engineer"

[contributors.links]
github = "bwasty"

[[contributors]]
name = "doomy"
about = "Designer & Rustacean"
description = "Working with the <a href=\"//amethyst.rs\">Amethyst Engine</a> team."

[contributors.links]
twitter = "piedoomy"
github = "piedoomy"
home = "https://u9h.design"

[[contributors]]
name = "ozkriff"
about = "System programmer, hobby game developer"
description = "Writes turn-based games in Rust (<a href=https://github.com/ozkriff/zemeroth>Zemeroth</a> atm), runs the <a href=https://twitter.com/rust_gamedev>@rust_gamedev</a> twitter account."

[contributors.links]
twitter = "ozkriff"
github = "ozkriff"
home = "https://ozkriff.games"

[[contributors]]
name = "17cupsofcoffee"
about = "Software engineer, hobbyist game dev"

[contributors.links]
twitter = "17cupsofcoffee"
github = "17cupsofcoffee"
home = "https://www.seventeencups.net/"
